# Generated by Django 3.2.16 on 2023-09-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_user_follow_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow',
            new_name='user',
        ),
    ]
